### ISSUE TITLE
DatagramStream typehint mismatch

### ISSUE THREAD

**Issue by spumer** [jsbronder/asyncio-dgram#11]
`drained` marked as `Queue` here:
https://github.com/jsbronder/asyncio-dgram/blob/d6cd9a1f418a94c808b995b08346c64e6968e900/asyncio_dgram/aio.pyi#L14

But real usage is still `Event` :)
https://github.com/jsbronder/asyncio-dgram/blob/d6cd9a1f418a94c808b995b08346c64e6968e900/asyncio_dgram/aio.py#L108

**Comment by jsbronder** [comment]
Fixed.  Thanks for the report!
