### ISSUE TITLE
Correct return type of sockname and peername

### ISSUE THREAD

**Issue by watsonjj** [jsbronder/asyncio-dgram#16]
Currently the sockname and peername properties are marked as returning str in the aio.pyi, but the return type is dependant on the address family:
https://docs.python.org/3/library/socket.html#socket-families

My suggestion is to use the _RetAddress TypeAlias for these properties (which alias to Any):
`from socket import _RetAddress`

**Comment by jsbronder** [comment]
Thanks for the report!
