### ISSUE TITLE
Could you make an updated release/tag?

### ISSUE THREAD

**Issue by Snuffy2** [jsbronder/asyncio-dgram#18]
I was trying to use the `reuse_port` attribute in bind and then realized that I'm running v2.1.2 from PyPi and that the addition of reuse_port hasn't been incorporated yet into a release. Any chance you could make an updated release with the commits since 2/2022?

**Comment by jsbronder** [comment]
Wow, I meant to do that quite a while ago.  Thanks for the reminder.  https://pypi.org/project/asyncio-dgram/2.2.0/

**Comment by Snuffy2** [comment]
Perfect, thank you!
