### ISSUE TITLE
Is there a specific reason there's no support for Python 3.5?

### ISSUE THREAD

**Issue by Iapetus-11** [jsbronder/asyncio-dgram#6]
I'm just wondering if it's an issue with compatibility or if it just hadn't been tested? Or if there's a different issue?

**Comment by jsbronder** [comment]
It hadn't been tested.  I went ahead and tried and the first blocker is that black requires 3.6+.  https://travis-ci.org/github/jsbronder/asyncio-dgram/builds/754304884

Looks like I need to migrate to github actions or circle ci anyways, so if I remember I'll revisit this then.  We don't need to run black for every version of python.

**Comment by Iapetus-11** [comment]
Alright thank you!

**Comment by jsbronder** [comment]
For what it's worth, 3.5 is supported in v1.2.0 now.  I just uploaded it to pypi.

**Comment by Iapetus-11** [comment]
Ah thank you!
